format = """
$directory$jobs\
$git_branch$git_state$git_status\
$python$nodejs
$character
"""

[jobs]
format = "[$symbol$number]($style) "
symbol = "ğŸš€"
number_threshold = 1
style = ""

[git_branch]
format = "\\([$branch]($style)"

[git_status]
format = "[$ahead_behind$stashed( [$staged$modified$untracked](#F48FB1))](#F2B482)\\) "

diverged = "$ahead$behind"
ahead = "â†‘$count"
behind = "â†“$count"

stashed = "â‰¡$count"
staged = "+$count"
untracked = "â€¦$count"
modified = "~$count"

[python]
style = "bold black"
symbol = "ğŸ“¦ "

[character]
success_symbol = "â¯"
error_symbol = "[â¯](#F48FB1)"

# â¯ or âœ
