format = """
$directory$jobs\
$git_branch$git_state$git_status\
$python$nodejs
$character
"""

[directory]
style = "#87DFEB"

[jobs]
format = "[$symbol$number]($style) "
symbol = "ğŸš€"
number_threshold = 1
style = ""

[git_branch]
format = "\\([$branch]($style)"
style = "#E0BCFF"

[git_status]
format = """
[$ahead_behind$stashed( \
[$staged$modified$untracked](#F48FB1))](#FFE6B3)\\) """

diverged = "$ahead$behind"
ahead = "â†‘$count"
behind = "â†“$count"

stashed = "â‰¡$count"
staged = "+$count"
untracked = "â€¦$count"
modified = "~$count"

[python]
symbol = "\\[py\\] "
style = "#8A889D"

[nodejs]
symbol = "\\[js\\] "
style = "#8A889D"

[character]
success_symbol = "â¯"
error_symbol = "[â¯](#F48FB1)"
# â¯ or âœ
